project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - math-237-example.qmd
    - math-437-example.qmd

website:
  title: "CSUF Math Example Projects"
  navbar:
    left:
#      - href: index.qmd
#        text: Home
      - href: math-237-example.qmd
        text: "Math 237"
      - href: math-437-example.qmd
        text: "Math 437"

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



