project:
  type: website
  output-dir: docs

website:
  title: "CSUF Math Example Projects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - math-237-example.qmd
      - href: math-437-example.qmd
        text: "Math 437"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



